"發生年度",
"發生月份",
"發生日期",
"發生時間",
"事故類別名稱",
"處理單位名稱警局層",
"發生地點",
"天候名稱",
"光線名稱",
"道路類別-第1當事者-名稱",
"速限-第1當事者",
"道路型態大類別名稱",
"道路型態子類別名稱",
"事故位置大類別名稱",
"事故位置子類別名稱",
"路面狀況-路面鋪裝名稱",
"路面狀況-路面狀態名稱",
"路面狀況-路面缺陷名稱",
"道路障礙-障礙物名稱",
"道路障礙-視距品質名稱",
"道路障礙-視距名稱",
"號誌-號誌種類名稱",
"號誌-號誌動作名稱",
"車道劃分設施-分向設施大類別名稱",
"車道劃分設施-分向設施子類別名稱",
"車道劃分設施-分道設施-快車道或一般車道間名稱",
"車道劃分設施-分道設施-快慢車道間名稱",
"車道劃分設施-分道設施-路面邊線名稱",
"事故類型及型態大類別名稱",
"事故類型及型態子類別名稱",
"肇因研判大類別名稱-主要",
"肇因研判子類別名稱-主要",
"死亡受傷人數",
"當事者順位",
"當事者區分-類別-大類別名稱-車種",
"當事者區分-類別-子類別名稱-車種",
"當事者屬-性-別名稱",
"當事者事故發生時年齡",
"保護裝備名稱",
"行動電話或電腦或其他相類功能裝置名稱",
"當事者行動狀態大類別名稱",
"當事者行動狀態子類別名稱",
"車輛撞擊部位大類別名稱-最初",
"車輛撞擊部位子類別名稱-最初",
"車輛撞擊部位大類別名稱-其他",
"車輛撞擊部位子類別名稱-其他",
"肇因研判大類別名稱-個別",
"肇因研判子類別名稱-個別",
"肇事逃逸類別名稱-是否肇逃",
"經度",
"緯度"



"Year of occurrence",
"Month of occurrence",
"Date of occurrence",
"The occurrence time",
"Accident category name",
"The processing unit name is the police station layer.",
"Location of occurrence",
"Weather name",
"Ray name",
"Road category - 1st party - name",
"Speed limit - First party",
"Road type categories name",
"Road type subcategory name",
"Accident Location Major Category Name",
"Accident location subcategory name",
"Road Conditions - Road Pavement Names",
"Road Conditions - Road Condition Names",
"Road Conditions - Road Surface Defect Name",
"Road obstruction - obstacle name",
"Road obstruction-visual distance quality name",
"Obstacle on the road - visibility name",
"Traffic signal - traffic signal type name",
"Signal - Signal Action Name",
"Roadway Lane Division Facilities - Categories Name for Lane Division Facilities",
"Road Marking Facilities - Subcategory Names for Lane Division Facilities",
"Road division facilities - Lane separation facilities - Name between express lanes or general lanes",
"Road division facilities - lane division facilities - name of the lane between the fast and slow lanes",
"Roadway division facilities - Dividing facilities - Road surface sidelines names",
"Types and categories of accident types and forms",
"Accident type and type subcategory name",
"The cause is determined to be the major category name - main.",
"The main cause of research inference-child categories name 主要",
"The number of deaths and injuries",
"Party Ranking",
"Party division - category - major category name - type of vehicle",
"Party Category Subcategory Name Vehicle Type",
"Party's gender identity",
"The age of the party at the time of the accident occurred",
"Protective equipment name",
"Mobile phone or computer or other similar functional device name",
"The name of the party's action state category",
"Party Action Status Subcategory Name",
"Vehicle impact site major category name - initial",
"Vehicle Collision Point Category Name - Initial",
"Vehicle collision location category name - Other",
"Vehicle impact area subcategory name - other",
"The cause is judged as a major category name - individual.",
"The cause is judged to be the category name - individual.",
"Hit and run category name - Are you a hit and run",
"Longitude",
"Latitude"




"Year",
"Month",
"Date",
"Time",
"Accident_Class",
"Police_Unit",
"Location",
"Weather",
"Light",
"Road_Type",
"Speed_Limit",
"Road_Shape",
"Road_Sub_Shape",
"Loc_Type",
"Loc_Sub_Type",
"Pavement_Type",
"Pavement_Status",
"Pavement_Defect",
"Obstacle",
"Sight_Quality",
"Sight",
"Signal_Type",
"Signal_Status",
"Lane_Div_Type",
"Lane_Div_Sub",
"Fast_Lane_Div",
"Fast_Slow_Div",
"Edge_Line",
"Accident_Type_Main",
"Accident_Type_Sub",
"Primary_Cause",
"Primary_Cause_Sub",
"Casualties",
"Party_Order",
"Vehicle_Class_Main",
"Vehicle_Class_Sub",
"Gender",
"Age",
"Protection",
"Mobile_Device",
"Action_Main",
"Action_Sub",
"Impact_Main",
"Impact_Sub",
"Impact_Other_Main",
"Impact_Other_Sub",
"Individual_Cause_Main",
"Individual_Cause_Sub",
"Hit_and_Run",
"Longitude",
"Latitude"